apiVersion: apps/v1
kind: Deployment
metadata:
  name: mockapp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mockapp
  template:
    metadata:
      labels:
        app: mockapp
    spec:
      containers:
        - name: mockapp
          image: mockapp:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"